services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Bookingtime\Appointment\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  Bookingtime\Appointment\Controller\AppointmentController:
    public: true
    arguments:
      $bookingtimeService: '@Bookingtime\Appointment\Service\BookingtimeService'
      $bookingtimepageurlRepository: '@Bookingtime\Appointment\Domain\Repository\BookingtimepageurlRepository'

  Bookingtime\Appointment\Service\BookingtimeService:
    public: true
    arguments:
      $bookingtimepageurlRepository: '@Bookingtime\Appointment\Domain\Repository\BookingtimepageurlRepository'
